# Generated by Django 5.2 on 2025-06-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(default='undefined', max_length=256),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
