# Generated by Django 5.2 on 2025-06-13 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0002_node_node_type_alter_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(max_length=256),
        ),
    ]
