# Generated by Django 5.1.5 on 2025-02-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blogpost_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='password_protect',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
