# Generated by Django 5.1.5 on 2025-02-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost_password_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='password_protect',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
    ]
