# Generated by Django 5.1.5 on 2025-02-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_blogpost_password_protect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="password_protect",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "true"), (False, "false")],
                default=False,
                null=True,
            ),
        ),
    ]
