# Generated by Django 5.1.5 on 2025-02-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_blogpost_password_protect"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="require_table_of_contents",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "true"), (False, "false")],
                default=False,
                null=True,
            ),
        ),
    ]
