# Generated by Django 5.1.5 on 2025-02-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_blogpost_require_table_of_contents"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True),
        ),
    ]
