# Generated by Django 5.1.5 on 2025-02-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_blogpost_options_alter_blogpost_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(default=None, related_name='blogposts', to='core.category'),
        ),
    ]
