# Generated by Django 5.1.5 on 2025-02-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_blogpost_password_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='password_protect',
            field=models.BooleanField(choices=[(True, 'true'), (False, 'false')], default=False),
        ),
    ]
