# Generated by Django 5.1.5 on 2025-02-12 04:06

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['last_modified']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
