# Generated by Django 5.1.5 on 2025-02-25 15:48

import django.db.models.deletion
import simple_history.models
import tinymce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_blogpost_options_alter_blogpost_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBlogPost',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('password_protect', models.BooleanField(blank=True, choices=[(True, 'true'), (False, 'false')], default=False, null=True)),
                ('require_table_of_contents', models.BooleanField(blank=True, choices=[(True, 'true'), (False, 'false')], default=False, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical blog post',
                'verbose_name_plural': 'historical blog posts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
